export default [
  {
    date: '2018/07/11',
    transactions: [
      {
        id: '-LK-Z9iJ3ntulXQ66Xhy',
        amount: '7000',
        category: 'comidas',
        date: '2018/07/11',
        description: '',
        title: 'Smothie',
      },
    ],
  },
  {
    date: '2018/07/13',
    transactions: [
      {
        id: '-LK-Z9iNHosh7IZnlhMf',
        amount: '11000',
        category: 'comidas',
        date: '2018/07/13',
        description: '',
        title: 'Empanadas',
      },
    ],
  },
  {
    date: '2018/07/14',
    transactions: [
      {
        id: '-LK-Z9iOMI-_odrsIkfK',
        amount: '12000',
        category: 'personal',
        date: '2018/07/14',
        description: '',
        title: 'Lapices y colores',
      },
      {
        id: '-LK-Z9iOMI-_odrsIkfL',
        amount: '20000',
        category: 'ropa',
        date: '2018/07/14',
        description: '',
        title: 'Calzoncillos',
      },
    ],
  },
  {
    date: '2018/07/16',
    transactions: [
      {
        id: '-LK-Z9iOMI-_odrsIkfM',
        amount: '100000',
        category: 'paseos',
        date: '2018/07/16',
        description: '',
        title: 'Alojamiento',
      },
      {
        id: '-LK-Z9iOMI-_odrsIkfN',
        amount: '49000',
        category: 'paseos',
        date: '2018/07/16',
        description: '',
        title: 'Tiquetes',
      },
      {
        id: '-LK-Z9iPpbRK7YzHOglq',
        amount: '16000',
        category: 'paseos',
        date: '2018/07/16',
        description: '',
        title: 'Comida en DUno',
      },
      {
        id: '-LK-Z9iPpbRK7YzHOglr',
        amount: '7500',
        category: 'paseos',
        date: '2018/07/16',
        description: '',
        title: 'Taxi a la casa',
      },
      {
        id: '-LK-Z9iPpbRK7YzHOgls',
        amount: '15000',
        category: 'paseos',
        date: '2018/07/16',
        description: '',
        title: 'Snacks',
      },
    ],
  },
  {
    date: '2018/07/17',
    transactions: [
      {
        id: '-LK-Z9iPpbRK7YzHOglt',
        amount: '5000',
        category: 'paseos',
        date: '2018/07/17',
        description: '',
        title: 'Buses',
      },
      {
        id: '-LK-Z9iPpbRK7YzHOglu',
        amount: '15000',
        category: 'paseos',
        date: '2018/07/17',
        description: '',
        title: 'Macanas',
      },
      {
        id: '-LK-Z9iQbeWtYRAVkKpD',
        amount: '12000',
        category: 'paseos',
        date: '2018/07/17',
        description: '',
        title: 'Museo el castillo',
      },
    ],
  },
  {
    date: '2018/07/18',
    transactions: [
      {
        id: '-LK-Z9iQbeWtYRAVkKpE',
        amount: '6000',
        category: 'paseos',
        date: '2018/07/18',
        description: '',
        title: 'Jugos',
      },
      {
        id: '-LK-Z9iQbeWtYRAVkKpF',
        amount: '7000',
        category: 'paseos',
        date: '2018/07/18',
        description: '',
        title: 'Almuerzo',
      },
      {
        id: '-LK-Z9iQbeWtYRAVkKpG',
        amount: '18000',
        category: 'paseos',
        date: '2018/07/18',
        description: '',
        title: 'Hamburguesa y Waffle',
      },
    ],
  },
  {
    date: '2018/07/19',
    transactions: [
      {
        id: '-LK-Z9iQbeWtYRAVkKpH',
        amount: '10000',
        category: 'paseos',
        date: '2018/07/19',
        description: '',
        title: 'Almuerzo',
      },
      {
        id: '-LK-Z9iQbeWtYRAVkKpI',
        amount: '12000',
        category: 'paseos',
        date: '2018/07/19',
        description: '',
        title: 'Metro',
      },
      {
        id: '-LK-Z9iR5pi4k_a_ccOa',
        amount: '10000',
        category: 'paseos',
        date: '2018/07/19',
        description: '',
        title: 'Uber',
      },
    ],
  },
  {
    date: '2018/07/20',
    transactions: [
      {
        id: '-LK-Z9iR5pi4k_a_ccOb',
        amount: '23000',
        category: 'paseos',
        date: '2018/07/20',
        description: '',
        title: 'Peajes Guarne',
      },
    ],
  },
  {
    date: '2018/07/21',
    transactions: [
      {
        id: '-LK-Z9iR5pi4k_a_ccOc',
        amount: '7000',
        category: 'paseos',
        date: '2018/07/21',
        description: '',
        title: 'Comida en Arvi',
      },
      {
        id: '-LK-Z9iR5pi4k_a_ccOd',
        amount: '13000',
        category: 'paseos',
        date: '2018/07/21',
        description: '',
        title: 'Perritos',
      },
      {
        id: '-LK-Z9iTogSGUMiON1jv',
        amount: '20000',
        category: 'paseos',
        date: '2018/07/21',
        description: '',
        title: 'Recarga Metro',
      },
      {
        id: '-LK-Z9iTogSGUMiON1jw',
        amount: '10000',
        category: 'paseos',
        date: '2018/07/21',
        description: '',
        title: 'Cervezas',
      },
    ],
  },
  {
    date: '2018/07/22',
    transactions: [
      {
        id: '-LK-Z9iU-2G9qFsfw-jV',
        amount: '12000',
        category: 'paseos',
        date: '2018/07/22',
        description: '',
        title: 'Cervezas',
      },
      {
        id: '-LK-Z9iU-2G9qFsfw-jW',
        amount: '37000',
        category: 'paseos',
        date: '2018/07/22',
        description: '',
        title: 'Hamburguesa ',
      },
    ],
  },
  {
    date: '2018/07/23',
    transactions: [
      {
        id: '-LK-Z9iU-2G9qFsfw-jX',
        amount: '12000',
        category: 'paseos',
        date: '2018/07/23',
        description: '',
        title: 'Salchipapa',
      },
      {
        id: '-LK-Z9iU-2G9qFsfw-jY',
        amount: '20000',
        category: 'paseos',
        date: '2018/07/23',
        description: '',
        title: 'Cosas en DUno',
      },
    ],
  },
  {
    date: '2018/07/24',
    transactions: [
      {
        id: '-LK-Z9iU-2G9qFsfw-jZ',
        amount: '16000',
        category: 'paseos',
        date: '2018/07/24',
        description: '',
        title: 'Almuerzo',
      },
      {
        id: '-LK-Z9iU-2G9qFsfw-j_',
        amount: '10000',
        category: 'paseos',
        date: '2018/07/24',
        description: '',
        title: 'Cosas en DUno',
      },
    ],
  },
  {
    date: '2018/07/25',
    transactions: [
      {
        id: '-LK-Z9iVbYjx84QYH4t_',
        amount: '24000',
        category: 'paseos',
        date: '2018/07/25',
        description: '',
        title: 'Ubers',
      },
      {
        id: '-LK-Z9iVbYjx84QYH4ta',
        amount: '10000',
        category: 'paseos',
        date: '2018/07/25',
        description: '',
        title: 'Subway',
      },
      {
        id: '-LK-Z9iVbYjx84QYH4tb',
        amount: '35000',
        category: 'paseos',
        date: '2018/07/25',
        description: '',
        title: 'Almuerzo en Ilforno',
      },
    ],
  },
  {
    date: '2018/07/26',
    transactions: [
      {
        id: '-LK-Z9iVbYjx84QYH4tc',
        amount: '12000',
        category: 'paseos',
        date: '2018/07/26',
        description: '',
        title: 'Almuerzo',
      },
    ],
  },
  {
    date: '2018/07/27',
    transactions: [
      {
        id: '-LK-Z9iVbYjx84QYH4td',
        amount: '8000',
        category: 'paseos',
        date: '2018/07/27',
        description: '',
        title: 'Taxi',
      },
      {
        id: '-LK-Z9iVbYjx84QYH4te',
        amount: '23000',
        category: 'paseos',
        date: '2018/07/27',
        description: '',
        title: 'Snacks',
      },
      {
        id: '-LK-Z9iWUEDdxiqKMLxH',
        amount: '50000',
        category: 'paseos',
        date: '2018/07/27',
        description: '',
        title: 'Regalo a la tia',
      },
    ],
  },
  {
    date: '2018/07/28',
    transactions: [
      {
        id: '-LK-Z9iWUEDdxiqKMLxI',
        amount: '15000',
        category: 'personal',
        date: '2018/07/28',
        description: '',
        title: 'Spotify',
      },
      {
        id: '-LK-Z9iWUEDdxiqKMLxJ',
        amount: '15000',
        category: 'comidas',
        date: '2018/07/28',
        description: '',
        title: 'Comina en Calarca con Lampre',
      },
    ],
  },
  {
    date: '2018/07/29',
    transactions: [
      {
        id: '-LK-Z9iWUEDdxiqKMLxK',
        amount: '18000',
        category: 'paseos',
        date: '2018/07/29',
        description: '',
        title: 'Caminata a Pijao',
      },
    ],
  },
  {
    date: '2018/07/30',
    transactions: [
      {
        id: '-LK-Z9iWUEDdxiqKMLxL',
        amount: '15000',
        category: 'personal',
        date: '2018/07/30',
        description: '',
        title: 'Cuchillas',
      },
    ],
  },
  {
    date: '2018/07/01',
    transactions: [
      {
        id: '-LK-Z9iWUEDdxiqKMLxM',
        amount: '159000',
        category: 'entretenimiento',
        date: '2018/07/01',
        description: '',
        title: 'Paseo a las cascadas de cordoba',
      },
    ],
  },
  {
    date: '2018/07/03',
    transactions: [
      {
        id: '-LK-Z9iXzIiyX9CHL3XV',
        amount: '8000',
        category: 'comidas',
        date: '2018/07/03',
        description: '',
        title: 'Pizza con Ricardo',
      },
    ],
  },
  {
    date: '2018/07/05',
    transactions: [
      {
        id: '-LK-Z9iXzIiyX9CHL3XW',
        amount: '6000',
        category: 'futbol',
        date: '2018/07/05',
        description: '',
        title: 'PArtido donde charli',
      },
      {
        id: '-LK-Z9iXzIiyX9CHL3XX',
        amount: '7000',
        category: 'comidas',
        date: '2018/07/05',
        description: '',
        title: 'Granizado',
      },
    ],
  },
  {
    date: '2018/07/06',
    transactions: [
      {
        id: '-LK-Z9iXzIiyX9CHL3XY',
        amount: '17000',
        category: 'entretenimiento',
        date: '2018/07/06',
        description: '',
        title: 'Cervezas en el norte',
      },
    ],
  },
  {
    date: '2018/07/07',
    transactions: [
      {
        id: '-LK-Z9iYIm1WfNhDs7iW',
        amount: '6000',
        category: 'comidas',
        date: '2018/07/07',
        description: '',
        title: 'Sandwich Yeye',
      },
    ],
  },
  {
    date: '2018/07/08',
    transactions: [
      {
        id: '-LK-Z9iYIm1WfNhDs7iX',
        amount: '7000',
        category: 'comidas',
        date: '2018/07/08',
        description: '',
        title: 'Crepe',
      },
    ],
  },
];
