export const CATEGORIES = {
  comidas: { label: 'Comidas', value: 'comidas' },
  compras_online: { label: 'Compras Online', value: 'compras_online' },
  educacion: { label: 'Educacion', value: 'educacion' },
  entretenimiento: { label: 'Entretenimiento', value: 'entretenimiento' },
  futbol: { label: 'Futbol', value: 'futbol' },
  hogar: { label: 'Hogar', value: 'hogar' },
  licor: { label: 'Licor', value: 'licor' },
  paseos: { label: 'Paseos', value: 'paseos' },
  personal: { label: 'Personal', value: 'personal' },
  regalos: { label: 'Regalos', value: 'regalos' },
  ropa: { label: 'Ropa', value: 'ropa' },
  snacks: { label: 'Snacks', value: 'snacks' },
  transporte: { label: 'Transporte', value: 'transporte' },
};
